### ISSUE TITLE
ISSUE-87: npm install fails on MacOS

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-client-node#58]
Original Issue: apache/pulsar-client-node#87 

---

### System Information
* Operating System: MacOS Catalina 10.15.2
* Node version: 12.13.1
* node-gyp version: 6.1.0
* C++ Client: 2.5.0 (brew install libpulsar)

Running `npm install pulsar-client` results in the following error:
```
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.1.0-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for pulsar-client@1.1.0 and node@12.13.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  CXX(target) Release/obj.target/Pulsar/src/addon.o
In file included from ../src/addon.cc:20:
../src/Message.h:24:10: fatal error: 'pulsar/c/message.h' file not found
#include <pulsar/c/message.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/Pulsar/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/richturnbull/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/Users/richturnbull/.nvm/versions/node/v12.13.1/bin/node" "/Users/richturnbull/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/richturnbull/dev/es/pulsar/client/node_modules/pulsar-client/build/Release/libpulsar.node" "--module_name=libpulsar" "--module_path=/Users/richturnbull/dev/es/pulsar/client/node_modules/pulsar-client/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/richturnbull/dev/es/pulsar/client/node_modules/pulsar-client
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/richturnbull/.nvm/versions/node/v12.13.1/bin/node /Users/richturnbull/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/richturnbull/dev/es/pulsar/client/node_modules/pulsar-client/build/Release/libpulsar.node --module_name=libpulsar --module_path=/Users/richturnbull/dev/es/pulsar/client/node_modules/pulsar-client/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/richturnbull/dev/es/pulsar/client/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command "/Users/richturnbull/.nvm/versions/node/v12.13.1/bin/node" "/Users/richturnbull/dev/es/pulsar/client/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/richturnbull/dev/es/pulsar/client/node_modules/pulsar-client
node-pre-gyp ERR! node -v v12.13.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/richturnbull/.nvm/versions/node/v12.13.1/bin/node /Users/richturnbull/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/richturnbull/dev/es/pulsar/client/node_modules/pulsar-client/build/Release/libpulsar.node --module_name=libpulsar --module_path=/Users/richturnbull/dev/es/pulsar/client/node_modules/pulsar-client/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN client@1.0.0 No description
npm WARN client@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pulsar-client@1.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pulsar-client@1.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richturnbull/.npm/_logs/2020-04-17T11_38_18_780Z-debug.log
```

**Comment by bulolo** [comment]
```
error /Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@12.18.3 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/build/Release/libpulsar.node" (not found)
node-pre-gyp http GET https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-darwin-x64.tar.gz
node-pre-gyp http 404 https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for pulsar-client@1.2.0 and node@12.18.3 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.2.0-node-v72-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.3 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.3 | darwin | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/hongjunyao/.node-gyp/12.18.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/hongjunyao/.node-gyp/12.18.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/hongjunyao/.node-gyp/12.18.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.3 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/nothing.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 20.4.0
gyp ERR! command "/usr/local/bin/node" "/Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/build/Release/libpulsar.node" "--module_name=libpulsar" "--module_path=/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/build/Release/libpulsar.node --module_name=libpulsar --module_path=/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/hongjunyao/Desktop/egg-mega-service/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 20.4.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/hongjunyao/Desktop/egg-mega-service/node_modules/pulsar-client
node-pre-gyp ERR! node -v v12.18.3
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
```

**Comment by xmsz** [comment]
any update?
